server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_commerce?createDatabaseIfNotExist=true
    username: root
    password: bssjanuary21

  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml
    enabled: true

  quartz:
    enabled: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

  kafka:
    producer:
      bootstrap-servers: localhost:9092

jobs:
  send-updates:
    cron-expression: 0/15 * * ? * * *